"""empty message

Revision ID: 526c6a80a57c
Revises: c3395afa9869
Create Date: 2018-04-23 14:22:45.772623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526c6a80a57c'
down_revision = 'c3395afa9869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('recipient_email', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'recipient_email')
    # ### end Alembic commands ###
